//【P1319】压缩技术 - 洛谷 - 0
#include <cmath>
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>
#include <map>

int main() {
	int n;
	std::cin >> n;
	bool YYF = false;
	int a, cnt = 0;
	while (std::cin >> a) {
		for (int i = 0; i < a; ++i) {
			std::cout << YYF;
			++cnt;
			if (cnt % n == 0)
				 std::cout << std::endl;
		}
		YYF = !YYF;
	}
}